import { Colors } from "@/constant/Colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    headerContainer: {
        overflow: "hidden",
    },
    headerBackground: {
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 24,
    },
    headerTop: {
        flexDirection: "row",
        alignItems: "flex-start",
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: "800",
        color: "#FFF",
        marginBottom: 12,
        letterSpacing: -0.5,
    },
    headerStats: {
        flexDirection: "row",
        gap: 12,
    },
    statBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
    },
    urgentBadge: {
        backgroundColor: "rgba(255, 107, 107, 0.2)",
    },
    statNumber: {
        fontSize: 16,
        fontWeight: "700",
        color: "#FFF",
    },
    statLabel: {
        fontSize: 12,
        fontWeight: "500",
        color: "#FFF",
        opacity: 0.9,
    },
    settingsButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        justifyContent: "center",
        alignItems: "center",
    },
    quickActions: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 12,
    },
    quickActionButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        paddingVertical: 14,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.3)",
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#FFF",
    },
    headerActions: {
        flexDirection: "row",
        gap: 12,
    },
    headerActionButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        paddingVertical: 10,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.2)",
    },
    headerActionText: {
        fontSize: 13,
        fontWeight: "600",
        color: "#FFF",
    },
    filtersContainer: {
        marginTop: 16,
        marginBottom: 8,
    },
    filtersContent: {
        paddingHorizontal: 24,
        gap: 10,
    },
    filterChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        marginRight: 10,
    },
    filterText: {
        fontSize: 14,
        fontWeight: "600",
    },
    filterBadge: {
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        paddingHorizontal: 6,
        justifyContent: "center",
        alignItems: "center",
        marginLeft: 6,
    },
    filterBadgeText: {
        fontSize: 11,
        fontWeight: "700",
    },
    notificationsContent: {
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 100,
    },
    notificationGroup: {
        marginBottom: 24,
    },
    dateHeader: {
        fontSize: 13,
        fontWeight: "700",
        marginBottom: 12,
        textTransform: "uppercase",
        letterSpacing: 0.5,
        opacity: 0.6,
    },
    notificationCard: {
        flexDirection: "row",
        padding: 16,
        borderRadius: 6,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "rgba(126, 124, 124, 0.2)",
        borderLeftWidth: 0,
    },
    notifIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 14,
    },
    notifContent: {
        flex: 1,
    },
    notifHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 6,
    },
    notifTitle: {
        fontSize: 16,
        fontWeight: "600",
        flex: 1,
        lineHeight: 20,
    },
    notifTitleUnread: {
        fontWeight: "700",
    },
    unreadDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: Colors.primary,
        marginLeft: 8,
    },
    notifMessage: {
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 10,
        opacity: 0.8,
    },
    notifFooter: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    footerLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    footerRight: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    notifTime: {
        fontSize: 12,
        opacity: 0.6,
    },
    priorityBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: "#FF6B6B15",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    priorityText: {
        fontSize: 11,
        fontWeight: "700",
        color: "#FF6B6B",
    },
    actionButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: Colors.primary + "15",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    cardIndicator: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        width: 4,
        borderTopLeftRadius: 20,
        borderBottomLeftRadius: 20,
    },
    actionButtonText: {
        fontSize: 12,
        fontWeight: "600",
        color: Colors.primary,
    },
    emptyState: {
        alignItems: "center",
        paddingVertical: 80,
    },
    emptyIcon: {
        width: 120,
        height: 120,
        borderRadius: 60,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 20,
    },
    emptyText: {
        fontSize: 20,
        fontWeight: "700",
        marginBottom: 8,
    },
    emptySubtext: {
        fontSize: 15,
        opacity: 0.6,
        textAlign: "center",
    },
    content: {
        flex: 1,
    },
    settingsHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    settingsTitle: {
        fontSize: 20,
        fontWeight: "700",
    },
    settingsSection: {
        paddingHorizontal: 24,
        marginTop: 24,
    },
    sectionHeaderSettings: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        marginBottom: 16,
    },
    sectionTitleSettings: {
        fontSize: 18,
        fontWeight: "700",
    },
    settingCard: {
        borderRadius: 6,
        overflow: "hidden",
        borderColor: "rgba(126, 124, 124, 0.2)",
        borderWidth: 1,
    },
    settingRowContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
    },
    settingRowClickable: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
    },
    settingLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        flex: 1,
    },
    settingIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: "center",
        alignItems: "center",
    },
    settingTitle: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 3,
    },
    settingSubtitle: {
        fontSize: 13,
        opacity: 0.6,
    },
    divider: {
        height: 1,
        marginLeft: 74,
    },
    modalContainer: {
        flex: 1,
        justifyContent: "flex-end",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingBottom: 40,
    },
    modalHandle: {
        width: 40,
        height: 4,
        backgroundColor: "#D1D5DB",
        borderRadius: 2,
        alignSelf: "center",
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: "700",
        marginBottom: 8,
    },
    modalDescription: {
        fontSize: 15,
        opacity: 0.6,
        marginBottom: 24,
    },
    inputContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 24,
    },
    modalInput: {
        flex: 1,
        padding: 16,
        borderRadius: 12,
        fontSize: 18,
        fontWeight: "600",
    },
    inputSuffix: {
        fontSize: 16,
        fontWeight: "600",
        marginLeft: 12,
        opacity: 0.6,
    },
    modalButtons: {
        flexDirection: "row",
        gap: 12,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    modalButtonPrimary: {
        backgroundColor: Colors.primary,
    },
    modalButtonTextPrimary: {
        fontSize: 16,
        fontWeight: "700",
        color: "#FFF",
    },
    modalButtonTextSecondary: {
        fontSize: 16,
        fontWeight: "600",
    },
});

export default styles;