import { Colors } from "@/constant/Colors";
import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    position: 'relative',
  },
  header: {
    position: 'absolute',
    paddingHorizontal: 10,
    paddingTop: 50,
    paddingBottom: 10,
    alignItems: 'flex-end',
    zIndex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
  },
  skipButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  skipText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  slide: {
    width,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 100,
  },
  illustrationContainer: {
    flex: 1,
    width: width * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  mainCircle: {
    width: 200,
    height: 200,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  darkCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cryptoIcon: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  bitcoin: {
    backgroundColor: '#F7931A',
    top: 40,
    left: 20,
  },
  ethereum: {
    backgroundColor: '#FF6B9D',
    bottom: 60,
    right: 20,
  },
  cryptoText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
  },
  smallCircle: {
    position: 'absolute',
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
  },
  purple: {
    width: 50,
    height: 50,
    backgroundColor: '#7C3AED',
    top: 50,
    right: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  blue: {
    width: 40,
    height: 40,
    backgroundColor: '#3B82F6',
    bottom: 40,
    left: 60,
  },
  yellow: {
    width: 35,
    height: 35,
    backgroundColor: '#FBBF24',
    top: 140,
    right: 80,
  },
  percentText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  securityCard: {
    width: 200,
    height: 240,
    borderRadius: 30,
    transform: [{ rotate: '10deg' }],
  },
  gradientCard: {
    flex: 1,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  lockIcon: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lockText: {
    fontSize: 40,
  },
  floatingDot: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  dot1: {
    backgroundColor: '#10B981',
    top: 20,
    left: 40,
  },
  dot2: {
    backgroundColor: '#FBBF24',
    bottom: 60,
    right: 20,
  },
  dot3: {
    backgroundColor: '#3B82F6',
    top: 100,
    right: 60,
  },
  chartCard: {
    width: 240,
    height: 160,
    borderRadius: 20,
  },
  chartGradient: {
    flex: 1,
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
  },
  chartBars: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 4,
  },
  bar: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderRadius: 4,
  },
  trendingBadge: {
    position: 'absolute',
    top: 20,
    right: 40,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FBBF24',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  trendingText: {
    fontSize: 24,
  },
  walletCard: {
    width: 200,
    height: 260,
    borderRadius: 25,
  },
  walletGradient: {
    flex: 1,
    borderRadius: 25,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  walletContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  chip: {
    width: 40,
    height: 30,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 6,
  },
  walletAmount: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    marginTop: 'auto',
  },
  walletDetails: {
    marginTop: 12,
  },
  detailLine: {
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderRadius: 4,
    marginBottom: 8,
  },
  shortLine: {
    width: '60%',
  },
  plusBadge: {
    position: 'absolute',
    bottom: 80,
    right: 30,
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: '#7C3AED',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '12deg' }],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  plusText: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
  },
  textContainer: {
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 16,
    lineHeight: 40,
  },
  description: {
    fontSize: 16,
    color: '#6B7280',
    lineHeight: 24,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    paddingHorizontal: 20,
    paddingBottom: 40,
    alignItems: 'center',
  },
  pagination: {
    flexDirection: 'row',
    marginBottom: 24,
    gap: 8,
  },
  dot: {
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.primary,
  },
  button: {
    width: '100%',
    height: 56,
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 16,
  },
  buttonGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.primary,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  browseButton: {
    paddingVertical: 12,
  },
  browseText: {
    color: '#7C3AED',
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles;