import { Colors } from "@/constant/Colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        height: 280,
        backgroundColor: Colors.primary,
    },
    headerBackground: {
        width: "100%",
        height: "100%",
        justifyContent: "space-between",
        paddingVertical: 24,
        paddingHorizontal: 20,
    },
    profileSection: {
        flexDirection: "row",
        alignItems: "center",
        gap: 20,
    },
    avatarWrapper: {
        position: "relative",
    },
    avatar: {
        width: 90,
        height: 90,
        borderRadius: 45,
        borderWidth: 3,
        borderColor: "#FFD700",
    },
    onlineBadge: {
        position: "absolute",
        bottom: 2,
        right: 2,
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: Colors.green,
        borderWidth: 3,
        borderColor: Colors.primary,
    },
    userName: {
        fontSize: 26,
        fontWeight: "800",
        color: "#FFF",
        marginBottom: 4,
    },
    cardIndicator: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        width: 4,
        borderTopLeftRadius: 20,
        borderBottomLeftRadius: 20,
    },
    userEmail: {
        fontSize: 14,
        color: "#FFF",
        opacity: 0.85,
        marginBottom: 8,
    },
    balanceContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
        marginTop: 4,
    },
    balanceText: {
        fontSize: 18,
        fontWeight: "700",
        color: "#FFD700",
    },
    statsContainer: {
        flexDirection: "row",
        gap: 12,
    },
    statCard: {
        flex: 1,
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        borderRadius: 6,
        padding: 9,
        paddingHorizontal: 9,
        alignItems: "center",
        backdropFilter: "blur(10px)",
    },
    statValue: {
        fontSize: 22,
        fontWeight: "800",
        color: "#FFF",
        marginTop: 8,
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 11,
        color: "#FFF",
        opacity: 0.9,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 8,
    },
    section: {
        marginBottom: 8,
    },
    modernIconContainer: {
        width: 80,
        height: 80,
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginTop: 24,
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "700",
    },
    menuItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 16,
        borderRadius: 6,
        marginBottom: 10,
        borderWidth: 1,
        borderLeftWidth: 0,
        borderColor: "rgba(126, 124, 124, 0.2)",
    },
    menuLeft: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
        gap: 14,
    },
    menuIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: "center",
        alignItems: "center",
    },
    menuTitle: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 3,
    },
    menuSubtitle: {
        fontSize: 13,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        justifyContent: "flex-end",
    },
    modalContent: {
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        paddingTop: 8,
        maxHeight: "92%",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 20,
    },
    modalTitle: {
        fontSize: 28,
        fontWeight: "800",
        letterSpacing: -0.5,
        marginBottom: 4,
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    modalBody: {
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    avatarSection: {
        alignItems: "center",
        paddingVertical: 28,
    },
    avatarContainers: {
        position: "relative",
        marginBottom: 12,
    },
    avatars: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 4,
        borderColor: Colors.green,
    },
    avatarEditButton: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: Colors.primary,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 4,
        borderColor: "#FFF",
    },
    avatarHint: {
        fontSize: 13,
        opacity: 0.7,
    },
    formGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 15,
        fontWeight: "600",
        marginBottom: 10,
    },
    input: {
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 6,
        fontSize: 16,
    },
    textArea: {
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 6,
        fontSize: 16,
        minHeight: 120,
    },
    passwordContainer: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 6,
    },
    passwordInput: {
        flex: 1,
        fontSize: 16,
    },
    divider: {
        height: 1,
        backgroundColor: "#E5E5E5",
        marginVertical: 24,
    },
    sectionSubtitle: {
        fontSize: 18,
        fontWeight: "700",
        marginBottom: 16,
    },
    generateButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 14,
        borderRadius: 6,
        marginBottom: 20,
    },
    generateButtonText: {
        fontSize: 15,
        fontWeight: "600",
    },
    buttonContainer: {
        marginVertical: 24,
        gap: 12,
    },
    saveButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 16,
        borderRadius: 6,
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: "700",
        color: "#FFF",
    },
    cancelButton: {
        paddingVertical: 16,
        borderRadius: 6,
        alignItems: "center",
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: "600",
    },
    modalDescription: {
        fontSize: 15,
        marginBottom: 24,
        opacity: 0.7,
        lineHeight: 22,
    },
    exportOption: {
        flexDirection: "row",
        alignItems: "center",
        gap: 16,
        padding: 16,
        backgroundColor: Colors.primary + "08",
        borderRadius: 6,
        marginBottom: 12,
    },
    exportTitle: {
        fontSize: 17,
        fontWeight: "700",
        marginBottom: 2,
    },
    exportDesc: {
        fontSize: 13,
        opacity: 0.6,
    },
    backupInfo: {
        alignItems: "center",
        paddingVertical: 32,
    },
    backupStatus: {
        fontSize: 18,
        fontWeight: "600",
        marginTop: 16,
        marginBottom: 4,
    },
    backupDate: {
        fontSize: 15,
        fontWeight: "600",
    },
    backupOptions: {
        gap: 12,
        marginTop: 16,
    },
    backupButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 16,
        borderRadius: 6,
    },
    backupButtonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#FFF",
    },
    reportOption: {
        flexDirection: "row",
        alignItems: "center",
        gap: 16,
        padding: 16,
        backgroundColor: Colors.primary + "05",
        borderRadius: 6,
        marginBottom: 12,
    },
    reportIcon: {
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: "center",
        alignItems: "center",
    },
    reportTitle: {
        fontSize: 17,
        fontWeight: "700",
        marginBottom: 2,
    },
    reportDesc: {
        fontSize: 13,
        opacity: 0.6,
    },
    faqItem: {
        marginBottom: 24,
        paddingBottom: 24,
        borderBottomWidth: 1,
        borderBottomColor: "#E5E5E5",
    },
    faqQuestion: {
        fontSize: 16,
        fontWeight: "700",
        marginBottom: 8,
    },
    faqAnswer: {
        fontSize: 15,
        lineHeight: 22,
        opacity: 0.7,
    },
    contactSection: {
        alignItems: "center",
        paddingVertical: 24,
    },
    contactTitle: {
        fontSize: 20,
        fontWeight: "700",
        marginTop: 16,
        marginBottom: 8,
    },
    contactDesc: {
        fontSize: 15,
        opacity: 0.7,
        textAlign: "center",
    },
    contactMethods: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 20,
        marginBottom: 24,
    },
    contactMethod: {
        alignItems: "center",
        gap: 8,
    },
    contactMethodText: {
        fontSize: 13,
        fontWeight: "600",
    },
    ratingSection: {
        alignItems: "center",
        paddingVertical: 24,
    },
    ratingTitle: {
        fontSize: 22,
        fontWeight: "700",
        marginTop: 16,
        marginBottom: 8,
        textAlign: "center",
    },
    ratingDesc: {
        fontSize: 15,
        opacity: 0.7,
        textAlign: "center",
    },
    starsContainer: {
        flexDirection: "row",
        justifyContent: "center",
        gap: 8,
        marginVertical: 24,
    },
    termsContent: {
        paddingBottom: 24,
    },
    termsSection: {
        fontSize: 15,
        lineHeight: 24,
        marginBottom: 20,
    },
    termsBold: {
        fontWeight: "700",
        fontSize: 16,
    },
    termsUpdate: {
        fontSize: 13,
        opacity: 0.6,
        marginTop: 16,
        fontStyle: "italic",
    },
    privacyHeader: {
        alignItems: "center",
        paddingVertical: 24,
    },
    privacyTitle: {
        fontSize: 20,
        fontWeight: "700",
        marginTop: 12,
        textAlign: "center",
    },
    privacyBadges: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 24,
        marginBottom: 16,
    },
    privacyBadge: {
        alignItems: "center",
        gap: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: Colors.green + "15",
        borderRadius: 12,
    },
    badgeText: {
        fontSize: 12,
        fontWeight: "600",
    },
});

export default styles