import { Colors } from "@/constant/Colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
     floatingCircle1: {
        position: 'absolute',
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: 'rgba(255,255,255,0.1)',
        top: -100,
        right: -50,
    },
    floatingCircle2: {
        position: 'absolute',
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: 'rgba(255,255,255,0.08)',
        bottom: 50,
        left: -50,
    },
    content: {
        flex: 1,
    },
    headerContainer: {
        height: 365
    },
    headerBackground: {
        width: "100%",
        height: "100%",
    },
    headerContent: {
        padding: 16,
        paddingHorizontal: 24,
    },
    headerTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 24,
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: "800",
        color: "#FFF",
        letterSpacing: -0.5,
        marginBottom: 4,
    },
    headerSubtitle: {
        fontSize: 14,
        color: "rgba(255, 255, 255, 0.85)",
        fontWeight: "500",
    },
    headerIconButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        justifyContent: "center",
        alignItems: "center",
    },
    modernOverviewCard: {
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        backdropFilter: "blur(10px)",
        borderRadius: 6,
        padding: 20,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.2)",
    },
    overviewMainInfo: {
        flexDirection: "row",
        marginBottom: 16,
    },
    overviewLeft: {
        flex: 1,
    },
    overviewLabel: {
        fontSize: 12,
        color: "rgba(255, 255, 255, 0.8)",
        fontWeight: "600",
        marginBottom: 8,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    overviewValue: {
        fontSize: 24,
        fontWeight: "800",
        color: "#FFF",
        letterSpacing: -0.5,
        marginBottom: 12,
    },
    overviewProgress: {
        gap: 8,
    },
    progressBarContainer: {
        height: 8,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        borderRadius: 4,
        overflow: "hidden",
    },
    progressBarFill: {
        height: "100%",
        backgroundColor: "#FFA500",
        borderRadius: 4,
    },
    progressPercentage: {
        fontSize: 13,
        color: "#FFF",
        fontWeight: "700",
    },
    overviewDivider: {
        width: 1,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        marginHorizontal: 20,
    },
    overviewRight: {
        flex: 1,
    },
    statsContainer: {
        flexDirection: "row",
        gap: 10,
    },
    modernStatBadge: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        padding: 10,
        borderRadius: 6,
    },
    statBadgeIcon: {
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: "center",
        alignItems: "center",
    },
    statBadgeText: {
        fontSize: 12,
        color: "#FFF",
        fontWeight: "700",
        flex: 1,
    },
    section: {
        paddingHorizontal: 20,
        marginTop: 24,
    },
    sectionHeader: {
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: "800",
        letterSpacing: -0.5,
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 13,
        fontWeight: "500",
    },
    modernGoalCard: {
        padding: 20,
        borderRadius: 6,
        marginBottom: 16,
        borderWidth: 1,
        borderLeftWidth: 0,
        borderColor: "rgba(126, 124, 124, 0.2)",
        position: "relative",
        overflow: "hidden",
    },
    modernGoalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 20,
    },
    goalHeaderLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        flex: 1,
    },
    modernGoalIcon: {
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: "center",
        alignItems: "center",
    },
    goalHeaderInfo: {
        flex: 1,
        gap: 6,
    },
    modernGoalTitle: {
        fontSize: 18,
        fontWeight: "700",
        letterSpacing: -0.3,
    },
    categoryBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    categoryDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    modernGoalCategory: {
        fontSize: 13,
        fontWeight: "500",
    },
    modernCompletedBadge: {
        width: 40,
        height: 40,
    },
    completedBadgeGradient: {
        width: "100%",
        height: "100%",
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    modernAmountsContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
        paddingVertical: 16,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.05)",
    },
    amountBox: {
        flex: 1,
    },
    modernAmountLabel: {
        fontSize: 12,
        fontWeight: "600",
        marginBottom: 6,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    modernAmountValue: {
        fontSize: 18,
        fontWeight: "800",
        letterSpacing: -0.3,
    },
    modernAmountDivider: {
        width: 1,
        height: 44,
        marginHorizontal: 20,
    },
    modernProgressContainer: {
        marginBottom: 16,
    },
    progressHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    progressLabel: {
        fontSize: 14,
        fontWeight: "700",
    },
    remainingLabel: {
        fontSize: 13,
        fontWeight: "600",
    },
    modernProgressBar: {
        height: 10,
        borderRadius: 5,
        overflow: "hidden",
    },
    modernProgressFill: {
        height: "100%",
        borderRadius: 5,
    },
    modernSuggestionCard: {
        padding: 16,
        borderRadius: 16,
        gap: 12,
    },
    suggestionHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    suggestionIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
    },
    modernSuggestionTitle: {
        fontSize: 15,
        fontWeight: "700",
        flex: 1,
    },
    modernSuggestionText: {
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "500",
    },
    modernDeadlineContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    modernDeadlineText: {
        fontSize: 12,
        fontWeight: "600",
    },
    goalColorIndicator: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        width: 4,
        borderTopLeftRadius: 20,
        borderBottomLeftRadius: 20,
    },
    modernEmptyState: {
        alignItems: "center",
        paddingVertical: 60,
        gap: 16,
    },
    emptyStateIcon: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: "rgba(99, 102, 241, 0.1)",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 8,
    },
    emptyTitle: {
        fontSize: 22,
        fontWeight: "700",
    },
    emptySubtext: {
        fontSize: 14,
        textAlign: "center",
        maxWidth: 280,
        lineHeight: 20,
    },
    emptyStateButton: {
        marginTop: 8,
        borderRadius: 16,
        overflow: "hidden",
    },
    emptyStateButtonGradient: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 24,
        paddingVertical: 14,
        gap: 8,
    },
    emptyStateButtonText: {
        color: "#FFF",
        fontSize: 15,
        fontWeight: "700",
    },
    modernAddButton: {
        position: "absolute",
        bottom: 120,
        right: 24,
        width: 64,
        height: 64,
        borderRadius: 32,
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 16,
        elevation: 10,
    },
    addButtonGradient: {
        width: "100%",
        height: "100%",
        borderRadius: 32,
        justifyContent: "center",
        alignItems: "center",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        justifyContent: "flex-end",
    },
    modalContent: {
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        paddingTop: 24,
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 28,
        fontWeight: "800",
        letterSpacing: -0.5,
        marginBottom: 4,
    },
    modalSubtitle: {
        fontSize: 14,
        fontWeight: "500",
    },
    modalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    modernInputGroup: {
        marginBottom: 20,
    },
    modernInputLabel: {
        fontSize: 15,
        fontWeight: "700",
        marginBottom: 10,
    },
    modernInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 6,
        gap: 12,
    },
    modernInput: {
        flex: 1,
        fontSize: 16,
        fontWeight: "500",
    },
    currencyLabel: {
        fontSize: 14,
        fontWeight: "600",
    },
    categoryScroll: {
        marginTop: 8,
    },
    modernCategoryChip: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 16,
        marginRight: 10,
        borderWidth: 2,
        gap: 8,
    },
    categoryChipIconContainer: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
    },
    modernCategoryChipText: {
        fontSize: 14,
        fontWeight: "600",
    },
    modernSubmitButton: {
        marginTop: 24,
        borderRadius: 6,
        marginBottom: 24,
        overflow: "hidden",
    },
    submitButtonDisabled: {
        opacity: 0.5,
    },
    submitButtonGradient: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 16,
        gap: 8,
    },
    modernSubmitButtonText: {
        color: "#FFF",
        fontSize: 17,
        fontWeight: "700",
    },
    contributeModal: {
        maxHeight: "90%",
    },
    modernGoalPreview: {
        alignItems: "center",
        marginBottom: 28,
        paddingBottom: 24,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0, 0, 0, 0.05)",
    },
    modernGoalPreviewIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 16,
    },
    modernGoalPreviewTitle: {
        fontSize: 22,
        fontWeight: "800",
        marginBottom: 12,
        letterSpacing: -0.3,
    },
    goalPreviewProgress: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 12,
    },
    goalPreviewAmount: {
        fontSize: 18,
        fontWeight: "800",
    },
    goalPreviewSeparator: {
        fontSize: 16,
        fontWeight: "600",
    },
    goalPreviewTarget: {
        fontSize: 16,
        fontWeight: "600",
    },
    previewProgressBar: {
        width: "100%",
        height: 6,
        borderRadius: 3,
        overflow: "hidden",
    },
    previewProgressFill: {
        height: "100%",
        borderRadius: 3,
    },
    modernAmountInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderRadius: 6,
        gap: 12,
    },
    modernAmountInput: {
        flex: 1,
        fontSize: 32,
        fontWeight: "800",
        textAlign: "center",
    },
    amountCurrency: {
        fontSize: 16,
        fontWeight: "600",
    },
    modernQuickAmounts: {
        marginBottom: 16,
    },
    quickAmountsLabel: {
        fontSize: 13,
        fontWeight: "600",
        marginBottom: 12,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    quickAmountsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
    },
    modernQuickAmountButton: {
        flex: 1,
        minWidth: "47%",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 14,
        borderRadius: 6,
        gap: 6,
        borderWidth: 2,
    },
    modernQuickAmountText: {
        fontSize: 14,
        fontWeight: "700",
    },
});

export default styles;