import { Colors } from "@/constant/Colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    modernHeader: {
        paddingTop: 16,
        paddingBottom: 20,
        paddingHorizontal: 20,
    },
    headerTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: "800",
        letterSpacing: -0.5,
        marginBottom: 4,
    },
    headerSubtitle: {
        fontSize: 14,
        fontWeight: "500",
    },
    headerIconButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: "rgba(99, 102, 241, 0.1)",
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    modernFilterBadge: {
        position: "absolute",
        top: -2,
        right: -2,
        backgroundColor: "#FF6B6B",
        width: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#FFF",
    },
    filterBadgeText: {
        color: "#FFF",
        fontSize: 10,
        fontWeight: "800",
    },
    summaryContainer: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 25,
        height: 150,
    },
    summaryCard: {
        flexDirection: "row",
        alignItems: "center",
        padding: 12,
        borderRadius: 6,
        gap: 10,
    },
    summaryIconContainer: {
        width: 40,
        height: 40,
    },
    summaryIconGradient: {
        width: "100%",
        height: "100%",
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    summaryInfo: {
        flex: 1,
    },
    summaryLabel: {
        fontSize: 11,
        fontWeight: "600",
        marginBottom: 4,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    summaryAmount: {
        fontSize: 15,
        fontWeight: "800",
        letterSpacing: -0.3,
    },
    modernSearchBar: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 6,
        gap: 12,
    },
    modernSearchInput: {
        flex: 1,
        fontSize: 15,
        fontWeight: "500",
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    dateSection: {
        marginTop: 24,
    },
    modernDateHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
        paddingHorizontal: 4,
    },
    dateHeaderLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    dateBadge: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: "center",
        alignItems: "center",
    },
    dateHeaderText: {
        fontSize: 18,
        fontWeight: "700",
        letterSpacing: -0.3,
    },
    transactionCount: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    countText: {
        fontSize: 13,
        fontWeight: "700",
    },
    transactionsList: {
        gap: 12,
    },
    modernTransactionCard: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
        borderRadius: 6,
        borderWidth: 1,
        // borderLeftWidth: 0,
        borderColor: "rgba(126, 124, 124, 0.2)",
    },
    transactionLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        flex: 1,
    },
    modernIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: "center",
        alignItems: "center",
    },
    transactionDetails: {
        flex: 1,
        gap: 6,
    },
    modernTransactionTitle: {
        fontSize: 16,
        fontWeight: "700",
        letterSpacing: -0.2,
    },
    categoryBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    categoryDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    modernTransactionCategory: {
        fontSize: 13,
        fontWeight: "500",
    },
    transactionRight: {
        alignItems: "flex-end",
        gap: 6,
    },
    modernTransactionAmount: {
        fontSize: 17,
        fontWeight: "800",
        letterSpacing: -0.3,
    },
    typeBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
    },
    typeBadgeText: {
        fontSize: 11,
        fontWeight: "700",
    },
    cardIndicator: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        width: 4,
        borderTopLeftRadius: 20,
        borderBottomLeftRadius: 20,
    },
    emptyState: {
        alignItems: "center",
        paddingVertical: 80,
        gap: 12,
    },
    emptyTitle: {
        fontSize: 22,
        fontWeight: "700",
    },
    emptyMessage: {
        fontSize: 14,
        textAlign: "center",
    },
    modernAddButton: {
        position: "absolute",
        bottom: 120,
        right: 24,
        width: 64,
        height: 64,
        borderRadius: 32,
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 16,
        elevation: 10,
    },
    addButtonGradient: {
        width: "100%",
        height: "100%",
        borderRadius: 32,
        justifyContent: "center",
        alignItems: "center",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        justifyContent: "flex-end",
    },
    modalContent: {
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        paddingTop: 24,
        paddingHorizontal: 24,
        paddingBottom: 40,
        maxHeight: "90%",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 28,
        fontWeight: "800",
        letterSpacing: -0.5,
        marginBottom: 4,
    },
    modalSubtitle: {
        fontSize: 14,
        fontWeight: "500",
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    modernTypeSelector: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 24,
    },
    modernTypeButton: {
        flex: 1,
        borderRadius: 6,
        overflow: "hidden",
        position: "relative",
    },
    typeButtonGradient: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    typeButtonContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 16,
        gap: 8,
    },
    typeButtonExpenseActive: {
        borderWidth: 0,
    },
    typeButtonIncomeActive: {
        borderWidth: 0,
    },
    modernTypeButtonText: {
        fontSize: 16,
        fontWeight: "700",
    },
    modernInputGroup: {
        marginBottom: 20,
    },
    modernInputLabel: {
        fontSize: 15,
        fontWeight: "700",
        marginBottom: 10,
    },
    modernInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 6,
        gap: 12,
    },
    modernInput: {
        flex: 1,
        fontSize: 16,
        fontWeight: "500",
    },
    currencyLabel: {
        fontSize: 14,
        fontWeight: "600",
    },
    categoryScroll: {
        marginTop: 8,
    },
    modernCategoryChip: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 16,
        marginRight: 10,
        borderWidth: 2,
        gap: 8,
    },
    categoryChipIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
    },
    modernCategoryChipText: {
        fontSize: 14,
        fontWeight: "600",
    },
    modernTextAreaContainer: {
        flexDirection: "row",
        alignItems: "flex-start",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 6,
        gap: 12,
    },
    textAreaIcon: {
        marginTop: 2,
    },
    modernTextArea: {
        flex: 1,
        fontSize: 16,
        fontWeight: "500",
        minHeight: 80,
        textAlignVertical: "top",
    },
    modernSubmitButton: {
        marginTop: 24,
        borderRadius: 6,
        overflow: "hidden",
    },
    submitButtonDisabled: {
        opacity: 0.5,
    },
    submitButtonGradient: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 16,
        gap: 8,
    },
    modernSubmitButtonText: {
        color: "#FFF",
        fontSize: 17,
        fontWeight: "700",
    },
    filterModal: {
        maxHeight: "80%",
    },
    modernFilterSection: {
        marginBottom: 28,
    },
    filterSectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        marginBottom: 14,
    },
    modernFilterSectionTitle: {
        fontSize: 17,
        fontWeight: "700",
    },
    modernFilterOptions: {
        gap: 10,
    },
    modernFilterOption: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 6,
        borderWidth: 2,
        gap: 12,
    },
    modernFilterOptionText: {
        flex: 1,
        fontSize: 15,
        fontWeight: "600",
    },
    filterActions: {
        flexDirection: "row",
        gap: 12,
        marginTop: 16,
    },
    modernResetButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 14,
        borderRadius: 6,
        gap: 8,
    },
    modernResetButtonText: {
        fontSize: 15,
        fontWeight: "700",
    },
    modernApplyButton: {
        flex: 1,
        borderRadius: 6,
        overflow: "hidden",
    },
    applyButtonGradient: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 14,
        gap: 8,
    },
    modernApplyButtonText: {
        color: "#FFF",
        fontSize: 15,
        fontWeight: "700",
    },
});


export default styles;